//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterReminder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonsterReminder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ButtonRegisterContent {
            get {
                return ResourceManager.GetString("ButtonRegisterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string ButtonReminderContent {
            get {
                return ResourceManager.GetString("ButtonReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Current Reminder.
        /// </summary>
        public static string ButtonStopReminder {
            get {
                return ResourceManager.GetString("ButtonStopReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple test with JSon.
        /// </summary>
        public static string ButtonTestContent {
            get {
                return ResourceManager.GetString("ButtonTestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Application.
        /// </summary>
        public static string CtxMenuQuit {
            get {
                return ResourceManager.GetString("CtxMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Current Reminder.
        /// </summary>
        public static string CtxMenuRemove {
            get {
                return ResourceManager.GetString("CtxMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should see an icon in the tray..
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Duration (min).
        /// </summary>
        public static string LabelFieldReminderDuration {
            get {
                return ResourceManager.GetString("LabelFieldReminderDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pouf and pouf.
        /// </summary>
        public static string ResourceKeyTest {
            get {
                return ResourceManager.GetString("ResourceKeyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing To Drink....
        /// </summary>
        public static string StatusBarTextNoReminder {
            get {
                return ResourceManager.GetString("StatusBarTextNoReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Reminder.
        /// </summary>
        public static string TrayIconToolTip {
            get {
                return ResourceManager.GetString("TrayIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Reminder Configurator.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
